name: Deploy formiks frontend

on:
  push:
    branches:
      - frontendDeploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: "frontendDeploy"
      - name: Install OpenVPN
        run: |
          sudo apt update
          sudo apt install -y openvpn openvpn-systemd-resolved
      - name: Connect to VPN
        uses: "kota65535/github-openvpn-connect-action@v2"
        with:
          # config_file: .github/workflows/client.ovpn
          username: ${{ secrets.OVPN_USERNAME }}
          password: ${{ secrets.OVPN_PASSWORD }}
          # client_key: ${{ secrets.USER_KEY }}
      - name: Upload the source
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          # port: ${{ secrets.PORT }}
          source: "frontend/*,!frontend/node_modules/*,!frontend/.github/*,!frontend/README.md,!frontend/.gitignore"
          target: formiks/frontend
      - name: Use SSH
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd formiks/frontend
            rm -rf build
            export NODE_OPTIONS="--max-old-space-size=8192"
            yarn install
            yarn build
            echo ${{ secrets.SERVER_PASSWORD }} | sudo -S systemctl restart formiks.service
