name: Deploy backend
on:
  push:
    paths:
      - "backend/**"
jobs:
  build:
    name: Deploy
    runs-on: self-hosted
    steps:
      - name: install and build
        uses: appleboy/ssh-action@dce9d565de8d876c11d93fa4fe677c0285a66d78
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script_stop: true
          script: |
            cd /home/doublegrey/formiks
            git reset --hard origin/master &> /dev/null
            git pull &> /dev/null
            cd /home/doublegrey/formiks/backend
            /usr/local/go/bin/go get
            /usr/local/go/bin/go build
            sudo systemctl restart formiks.service
