name: deploy [staging]
on: [push]
jobs:
  build:
    name: Deploy
    runs-on: self-hosted
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@dce9d565de8d876c11d93fa4fe677c0285a66d78
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script_stop: true
        script: |
          cd formiks
          git pull &> /dev/null
          cd backend
          /usr/local/go/bin/go build
          sudo systemctl restart formiks.service
